### PR TITLE
Fix deep-copying of type-aliased primitives

### PR DESCRIPTION
**Pull request by atombender**
This also adds some more tests.

### CODE REVIEW

**Comment by atombender** [comment]
Oops, I did not see the message about this repo being deprecated. Will take a look at the replacement.

**Comment by mohae** [comment]
Where does it say that it's deprecated so I can fix that message?  It was...but then I rethought that decision and recently refactored this.

**Comment by atombender** [comment]
It was in the readme, which I see you've changed.

**Comment by mohae** [comment]
Oh, this was a while ago. Sorry I didn't notice this pull request sooner.  I wasn't ignoring it, it was an oversight.

I don't think this applies with the updated version of deepcopy.  I appreciate your attempt to contribute thought!

**Comment by atombender** [comment]
Does this mean that github.com/mohae/utilitybelt/deepcopy is the one that's deprecated now, and this is the main repo?

**Comment by mohae** [comment]
Yes.  The current readme for that is:

    This exists for legacy reasons so that anything that happens to use it will not break. See also deepcopy

Sorry for the confusion, but this package kept getting used, in spite of my deprecation note so I decided I should undeprecate it and clean up this repo and apply my fixes here.

Also the utilitybelt repo still has caveats in the README because of possibility that the stuff in there may change and/or may need additional testing and work.  I consider this one safe to use if one must use a generic deep copy function in Go.

There will not be any further api changes to this package unless it is required by a bug fix.

**Comment by atombender** [comment]
Thanks for the clarification. I _was_ using this repo first, then the other one. Back to this one, I guess!

**Comment by mohae** [comment]
Sorry!  I promise I won't change it again.

**Comment by atombender** [comment]
No problem. I prefer top-level packages.

**Pull request closed without merging**
